
[DEFAULT]
usernamekey=934399812
passwordkey=SergioMaldito1
#futuro username blrdmanrique@gmail.com
#contraseña  AbelardoMan23 - AbelardoMan23FB
[DB]
dbname=facebook_db
user=postgress
password=Taicho10
host=localhost
#934399812
#SergioMaldito1